applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'), 
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('listar-by-area/<shorname>/',
     views.ListByAreaEpleado.as_view(),
     name='empleados_area'
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'    
    ),
    path('add-empleado/',
     views.EmpleadoCreateView.as_view(),
     name='empleado_add'    
    ),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-user/<pk>',
     views.EmpleadoUpdateView.as_view(), 
     name='modificar_empleado'),
    path('delete-empleado/<pk>',
     views.EmpleadoDeleteView.as_view(),
      name='eliminar'),
    path('lista-empleados-admin/', 
        views.ListEpleadosAdmin.as_view(),
        name='empleados_admin'
    )

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    

    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls'))
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento, Habilidades
from ckeditor.fields import RichTextField


# Create your models here.
class Empleado(models.Model):
    # Modelo para tabla empleado
    # MUESTRA UNA LISTA DE EMPLEOS
    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTROS'),
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('apellidos', max_length=60)
    full_name = models.CharField('Nombres completos', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidad = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()



    # INFORMACION QUE SE MUESTRA EN EL ADMINISTRADOR
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['first_name']  #['-first_name'] descendente
        unique_together = ('first_name', 'last_name') #no permite tener los dos repetidos


    def __str__(self):
        return str(self.id) + '_' + self.first_name + '_' + self.last_name

applications/persona/forms.py
from django import forms
from django.forms import widgets
from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidad'
        )
        widgets = {
            'habilidad': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from django.shortcuts import render
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy

# Create your views here.
from .models import Empleado
from .forms import EmpleadoForm

# PROYECOT 1
class InicioView(TemplateView):
    template_name = 'home/inicio.html'


'''
REQUERIMIENTOS 
1. Listar todos los empleados de la empresa
2. listar todos los empleados que pertenecen a un area de la empresa
3. listar empleados por trabajo
4. listar empleados por palabra clave
5. listar habilidades de un empleado
'''

# listar todos los empleados de la empresa
class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4   # paginacion
    

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name__icontains = palabra_clave   # icontains busca similitudes en las cadenas 
        )
        return lista



# listar todos los empleados que pertenecen a un area de la empresa
class ListByAreaEpleado(ListView):
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
            departamento__shor_name = area
        ) 

        return lista



class ListEpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    context_object_name = 'empleados'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

    


# LISTAR EMPLEADOS POR PALABRA CLAVE  --- de los filtros mas utilizados
class ListEmpleadosByKword(ListView):
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'   #para acceder mejor desde el html con el nombre de empleados


    # Esta funcion es de django
    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        return lista



# LISTAR EMPLEADOS POR HABILIDADES
class ListHabilidadesEmpleado(ListView):
    template_name = 'persona/habilidades.html'
    context_object_name = 'habilidades'


    def get_queryset(self):
        empleado = Empleado.objects.get(id=4)
        return empleado.habilidad.all() 




# DELLES DEL EMPLEADO
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail_empleado.html' 


    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes' 
        return context            



class SuccessView(TemplateView):
    template_name = 'persona/success.html'


# VISTA PARA CREAR REGISTROS EN BD
class EmpleadoCreateView(CreateView):
    template_name = 'persona/add.html'  
    model = Empleado 
    form_class = EmpleadoForm
    success_url =  reverse_lazy('persona_app:empleados_admin')     #'.' para que se recargue la url en la misma pagina   


    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)




#  ACTUALIZAR UN USUARIO
class EmpleadoUpdateView(UpdateView):
    template_name = 'persona/update.html'
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        
        'habilidad',
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')



# ELIMINAR UN EMPLEADO
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'persona/delete.html'
    success_url = reverse_lazy('persona_app:empleados_admin')    

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
    Crear empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        
        <h1 class="cell">Crear persona</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="medium-6 cell">
                <label for="">Nombres</label>
                {{form.first_name}}
            </div>
            <div class="medium-6 cell">
                <label for="">Apellidos</label>
                {{form.last_name}}
            </div>
            <div class="medium-6 cell">
                <label for="">Trabajo</label>
                {{form.job}}
            </div>
            <div class="medium-6 cell">
                <label for="">Departamento</label>
                {{form.departamento}}
            </div>
            <div class="medium-12 cell">
                <label for="">Habilidad</label>
                {{form.habilidad}}
            </div>
            <div class="medium-12 cell">
                <label for="">Foto</label>
                {{form.avatar}}
            </div>
            <div class="medim-6 cell">

                <button type="submit" class="success button">Guardar</button>
            </div>
        
            
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/by_kword.html
<h1>Buscar empleado</h1>

<form method="GET">
    {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista resultados</h3>
<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}    
</ul>

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
    <h1 class="cell">Eliminar empleado {{ object.first_name }}</h1>
        <form class="cell" method="POST">
            {% csrf_token %}
            <div class="callout warning">
                <h5>Desea eliminar el empleado {{ object.first_name }} ?</h5>
                
                <button type="submit" class="alert button">Eliminar</button>
              </div>
           
        
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{object.full_name}}
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px;">
            <div class="card-divider">
              {{empleado.get_job_display}}
            </div>
            {% if empleado.avatar %}
                <img src="{{ empleado.avatar.url }}">
            {% else %}            
                <img src="{% static 'img/python1.png' %}">                
            {% endif %}
            <div class="card-section">
              <h4>{{empleado.first_name}}</h4>
              <p>{{empleado.last_name}}</p>
              <p>{{empleado.departamento.shor_name}}</p>
              <p><span class="label">Habilidades</span></p>
              <ul class="vertical menu">
                {% for h in empleado.habilidad.all %}
                <li>

                    {{ h.habilidad }}
                </li>
                {% endfor %}
              </ul>
              
            </div>
          </div>
    </div>
</div>

    




    
{% endblock content %}

templates/persona/habilidades.html
<h1>Lista habilidades empleados</h1>

{% for h in habilidades %}
    <li>
        {{h}}
    </li>
{% endfor %}

templates/persona/list_all.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">
            {% csrf_token %}

            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">Id</th>
                    <th>Nombres</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in object_list %}
                  <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a></td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>
        </div>
        <div class="cell">
          {% if is_paginated %}

            <nav aria-label="Pagination">
              <ul class="pagination">
                {% if page_obj.has_previous %}

                  <li class="pagination-previous ">
                    <a href="?page={{page_obj.previous_page_number}}" >Atras</a>
                  </li>
                {% endif %}
                {% for pagina in paginator.page_range %}

                {% if pagina == page_obj.number %}
                
                  <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                {% else %}  
                  <li><a href="?page={{pagina}}" >{{pagina}}</a></li> 
                {% endif %}   
                {% endfor %}
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{page_obj.next_page_number}}" >Siguiente</a>
                </li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
    </div>
    
</div>

{% endblock content %}

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title %}

    Lista de empleados por departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}
<h1> Lista de empleados por departamento</h1>

<div class="grid-content">
    <div class="grid-x">
        <div class="cell">Empleados por area</div>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">Id</th>
                    <th>Nombres</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                  </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                  <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.first_name}}</td>
                    <td>{{empleado.last_name}}</td>
                    <td>{{empleado.departamento}}</td>
                    <td><a class="button warning" href="">Ver</a></td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>

        </div>
    </div>
</div>



{% endblock content %}

templates/persona/lista_empleados.html
{% extends 'base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista empleados</h1>
        
        <div class="cell">
            <table>
                <thead>
                  <tr>
                    <th width="200">Id</th>
                    <th>Nombres</th>
                    <th width="150">Apellidos</th>
                    <th width="150">Departamento</th>
                    <th width="150">Acción</th>
                  </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                  <tr>
                    <td>{{empleado.id}}</td>
                    <td>{{empleado.first_name}}</td>
                    <td>{{empleado.last_name}}</td>
                    <td>{{empleado.departamento}}</td>
                    <td>
                        <a class="button success" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a>
                        
                    </td>
                    <td>
                        
                        <a class="button alert" href="{% url 'persona_app:eliminar' empleado.id %}">Eliminar</a>
                    </td>
                  </tr>
                  {% endfor %}
                  
                </tbody>
              </table>
        </div>
        <div class="cell">
          {% if is_paginated %}

            <nav aria-label="Pagination">
              <ul class="pagination">
                {% if page_obj.has_previous %}

                  <li class="pagination-previous ">
                    <a href="?page={{page_obj.previous_page_number}}" >Atras</a>
                  </li>
                {% endif %}
                {% for pagina in paginator.page_range %}

                {% if pagina == page_obj.number %}
                
                  <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                {% else %}  
                  <li><a href="?page={{pagina}}" >{{pagina}}</a></li> 
                {% endif %}   
                {% endfor %}
                
                {% if page_obj.has_next %}
                <li class="pagination-next">
                  <a href="?page={{page_obj.next_page_number}}" >Siguiente</a>
                </li>
                {% endif %}
              </ul>
            </nav>
          {% endif %}
        </div>
    </div>
    
</div>

{% endblock content %}

templates/persona/success.html
<h1>Registro creado</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
    Editar empleado
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">
            <h1>Modificar empleado</h1>
            <div class="cell">

                <form class="grid-x grid-margin-x" method="POST">
                    <div class="large-6 cell">
                        <label>Nombres
                          
                          {{form.first_name}}
                        </label>
                    </div>
                    <div class="large-6 cell">
                        <label>Apellidos
                          
                          {{form.last_name}}
                        </label>
                    </div>
                    <div class="large-6 cell">
                        <label>trabajo
                          
                          {{form.job}}
                        </label>
                    </div>
                    <div class="large-6 cell">
                        <label>Departamento
                          
                          {{form.departamento}}
                        </label>
                    </div>
                    <div class="large-6 cell">
                        <label>Hbilidades
                          
                          {{form.habilidad}}
                        </label>
                    </div>
                    <div class="cell">

                        <button type="submit" class="success button">Actualizar</button>
                    </div>
                    {% csrf_token %}
                
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock content %}