applications/departamento/urls.py
from django.urls import path
from django.contrib import admin


from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('lista-departamento', views.DepartamentoListView.as_view(), name='departamento_list')
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'), 
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('listar-by-area/<shorname>/',
     views.ListByAreaEpleado.as_view(),
     name='empleados_area'
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'    
    ),
    path('add-empleado/',
     views.EmpleadoCreateView.as_view(),
     name='empleado_add'    
    ),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-user/<pk>',
     views.EmpleadoUpdateView.as_view(), 
     name='modificar_empleado'),
    path('delete-empleado/<pk>',
     views.EmpleadoDeleteView.as_view(),
      name='eliminar'),
    path('lista-empleados-admin/', 
        views.ListEpleadosAdmin.as_view(),
        name='empleados_admin'
    )

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    

    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls'))
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li class="has-submenu">
        <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
        
      </li>
      <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
      <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
      <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar nuevo</a></li>
    </ul>
  </div>
</div>