applications/departamento/urls.py
from django.urls import path
from django.contrib import admin


from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('lista-departamento', views.DepartamentoListView.as_view(), name='departamento_list')
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from . import views

app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'), 
    path('listar-todo-empleados/',
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('listar-by-area/<shorname>/',
     views.ListByAreaEpleado.as_view(),
     name='empleados_area'
    ),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path('ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'    
    ),
    path('add-empleado/',
     views.EmpleadoCreateView.as_view(),
     name='empleado_add'    
    ),
    path('success/', views.SuccessView.as_view(), name='correcto'),
    path('update-user/<pk>',
     views.EmpleadoUpdateView.as_view(), 
     name='modificar_empleado'),
    path('delete-empleado/<pk>',
     views.EmpleadoDeleteView.as_view(),
      name='eliminar'),
    path('lista-empleados-admin/', 
        views.ListEpleadosAdmin.as_view(),
        name='empleados_admin'
    )

]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    

    path('', include('applications.home.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.departamento.urls'))
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)


    class Meta:
        verbose_name = 'Hbilidad'
        verbose_name_plural = 'Hbilidades empleados'


    def __str__(self):
        return str(self.id) + '-' + self.habilidad   



class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre corto', max_length=50)
    anulate = models.BooleanField('Anulado', default=False)



    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Area de la empresa'
        ordering = ['name']  #['-name'] descendente
        unique_together = ('name', 'shor_name') #no permite tener los dos repetidos


    def __str__(self):
        return self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from applications.departamento.models import Departamento
from django.views.generic import ListView

from applications.persona.models import Empleado
from .forms import NewDepartamentoForm

from .forms import NewDepartamentoForm

# Create your views here.

class DepartamentoListView(ListView):
    template_name = 'departamento/lista.html'
    model = Departamento
    context_object_name = 'departamentos'

class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'


    def form_valid(self, form):
        print('*****form**********')
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            job = '1',
            departamento = depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}


{% block title %}
    Lista departamentos
{% endblock %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.shor_name}}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %} ">Ver Empleado</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Nuevo departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar departamento</h1>

        <form class="cell callout grid-x grid-margin-x" method="POST">
            {% csrf_token %}
           <div class="medium-6 cell">
               <label for="">Nombres</label>
               {{form.nombre}}
           </div>
           <div class="medium-6 cell">
            <label for="">Apellidos</label>
            {{form.apellidos}}
        </div>
        <h3 class="cell">Datos de departamento</h3>
        <div class="medium-6 cell">
            <label for="">Departamento</label>
            {{form.departamento}}
        </div>
        <div class="medium-6 cell">
            <label for="">shorname</label>
            {{form.shorname}}
        </div>
            
            
            
            <button class="success button" type="submit">Guardar</button>
        </form>
    </div>
</div>
{% endblock content %}